live_config_reload = true
import = [
    "~/.config/alacritty/ubuntumonoNERD.toml", 
    "~/.config/alacritty/alacritty-auto-theme/theme.toml"
]
ipc_socket = true

[font]
size = 15.0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Control"

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"
decorations_theme_variant = "None"

[window.padding]
x = 3
y = 4
